#!/bin/sh
# Rename original SFM files to new filenames that come out of bibledit-desktop

git mv Manipuri_01GEN_MBU.SFM 01_Genesis.usfm		 
git mv Manipuri_02EXO_MBU.SFM 02_Exodus.usfm		 
git mv Manipuri_03LEV_MBU.SFM 03_Leviticus.usfm	 
git mv Manipuri_04NUM_MBU.SFM 04_Numbers.usfm		 
git mv Manipuri_05DEU_MBU.SFM 05_Deuteronomy.usfm	 
git mv Manipuri_06JOS_MBU.SFM 06_Joshua.usfm		 
git mv Manipuri_07JDG_MBU.SFM 07_Judges.usfm		 
git mv Manipuri_08RUT_MBU.SFM 08_Ruth.usfm		 
git mv Manipuri_091SA_MBU.SFM 09_1_Samuel.usfm	 
git mv Manipuri_102SA_MBU.SFM 10_2_Samuel.usfm	 
git mv Manipuri_111KI_MBU.SFM 11_1_Kings.usfm		 
git mv Manipuri_122KI_MBU.SFM 12_2_Kings.usfm		 
git mv Manipuri_131CH_MBU.SFM 13_1_Chronicles.usfm	 
git mv Manipuri_142CH_MBU.SFM 14_2_Chronicles.usfm	 
git mv Manipuri_15EZR_MBU.SFM 15_Ezra.usfm		 
git mv Manipuri_16NEH_MBU.SFM 16_Nehemiah.usfm	 
git mv Manipuri_17EST_MBU.SFM 17_Esther.usfm		 
git mv Manipuri_18JOB_MBU.SFM 18_Job.usfm		 
git mv Manipuri_19PSA_MBU.SFM 19_Psalms.usfm		 
git mv Manipuri_20PRO_MBU.SFM 20_Proverbs.usfm	 
git mv Manipuri_21ECC_MBU.SFM 21_Ecclesiastes.usfm	 
git mv Manipuri_22SNG_MBU.SFM 22_Song_of_Solomon.usfm	 
git mv Manipuri_23ISA_MBU.SFM 23_Isaiah.usfm		 
git mv Manipuri_24JER_MBU.SFM 24_Jeremiah.usfm	 
git mv Manipuri_25LAM_MBU.SFM 25_Lamentations.usfm	 
git mv Manipuri_26EZK_MBU.SFM 26_Ezekiel.usfm		 
git mv Manipuri_27DAN_MBU.SFM 27_Daniel.usfm		 
git mv Manipuri_28HOS_MBU.SFM 28_Hosea.usfm		 
git mv Manipuri_29JOL_MBU.SFM 29_Joel.usfm		 
git mv Manipuri_30AMO_MBU.SFM 30_Amos.usfm		 
git mv Manipuri_31OBA_MBU.SFM 31_Obadiah.usfm		 
git mv Manipuri_32JON_MBU.SFM 32_Jonah.usfm		 
git mv Manipuri_33MIC_MBU.SFM 33_Micah.usfm		 
git mv Manipuri_34NAM_MBU.SFM 34_Nahum.usfm		 
git mv Manipuri_35HAB_MBU.SFM 35_Habakkuk.usfm	 
git mv Manipuri_36ZEP_MBU.SFM 36_Zephaniah.usfm	 
git mv Manipuri_37HAG_MBU.SFM 37_Haggai.usfm		 
git mv Manipuri_38ZEC_MBU.SFM 38_Zechariah.usfm
git mv Manipuri_39MAL_MBU.SFM 39_Malachi.usfm

git mv Manipuri_41MAT_MBU.SFM 40_Matthew.usfm
git mv Manipuri_42MRK_MBU.SFM 41_Mark.usfm
git mv Manipuri_43LUK_MBU.SFM 42_Luke.usfm
git mv Manipuri_44JHN_MBU.SFM 43_John.usfm
git mv Manipuri_45ACT_MBU.SFM 44_Acts.usfm
git mv Manipuri_46ROM_MBU.SFM 45_Romans.usfm
git mv Manipuri_471CO_MBU.SFM 46_1_Corinthians.usfm
git mv Manipuri_482CO_MBU.SFM 47_2_Corinthians.usfm
git mv Manipuri_49GAL_MBU.SFM 48_Galatians.usfm
git mv Manipuri_50EPH_MBU.SFM 49_Ephesians.usfm
git mv Manipuri_51PHP_MBU.SFM 50_Philippians.usfm
git mv Manipuri_52COL_MBU.SFM 51_Colossians.usfm
git mv Manipuri_531TH_MBU.SFM 52_1_Thessalonians.usfm
git mv Manipuri_542TH_MBU.SFM 53_2_Thessalonians.usfm
git mv Manipuri_551TI_MBU.SFM 54_1_Timothy.usfm
git mv Manipuri_562TI_MBU.SFM 55_2_Timothy.usfm
git mv Manipuri_57TIT_MBU.SFM 56_Titus.usfm
git mv Manipuri_58PHM_MBU.SFM 57_Philemon.usfm
git mv Manipuri_59HEB_MBU.SFM 58_Hebrews.usfm
git mv Manipuri_60JAS_MBU.SFM 59_James.usfm
git mv Manipuri_611PE_MBU.SFM 60_1_Peter.usfm
git mv Manipuri_622PE_MBU.SFM 61_2_Peter.usfm
git mv Manipuri_631JN_MBU.SFM 62_1_John.usfm
git mv Manipuri_642JN_MBU.SFM 63_2_John.usfm
git mv Manipuri_653JN_MBU.SFM 64_3_John.usfm
git mv Manipuri_66JUD_MBU.SFM 65_Jude.usfm
git mv Manipuri_67REV_MBU.SFM 66_Revelation.usfm
