#!/bin/sh
# Rename what we had out of bibledit-desktop to the Paratext names that
# will be used going forward.

git mv 01_Genesis.usfm		    Manipuri_01GEN_MBU.SFM
git mv 02_Exodus.usfm		    Manipuri_02EXO_MBU.SFM
git mv 03_Leviticus.usfm	    Manipuri_03LEV_MBU.SFM
git mv 04_Numbers.usfm		    Manipuri_04NUM_MBU.SFM
git mv 05_Deuteronomy.usfm	    Manipuri_05DEU_MBU.SFM
git mv 06_Joshua.usfm		    Manipuri_06JOS_MBU.SFM
git mv 07_Judges.usfm		    Manipuri_07JDG_MBU.SFM
git mv 08_Ruth.usfm		    Manipuri_08RUT_MBU.SFM
git mv 09_1_Samuel.usfm	 	    Manipuri_091SA_MBU.SFM
git mv 10_2_Samuel.usfm	 	    Manipuri_102SA_MBU.SFM
git mv 11_1_Kings.usfm		    Manipuri_111KI_MBU.SFM
git mv 12_2_Kings.usfm		    Manipuri_122KI_MBU.SFM
git mv 13_1_Chronicles.usfm	    Manipuri_131CH_MBU.SFM
git mv 14_2_Chronicles.usfm	    Manipuri_142CH_MBU.SFM
git mv 15_Ezra.usfm		    Manipuri_15EZR_MBU.SFM
git mv 16_Nehemiah.usfm	 	    Manipuri_16NEH_MBU.SFM
git mv 17_Esther.usfm		    Manipuri_17EST_MBU.SFM
git mv 18_Job.usfm		    Manipuri_18JOB_MBU.SFM
git mv 19_Psalms.usfm		    Manipuri_19PSA_MBU.SFM
git mv 20_Proverbs.usfm	 	    Manipuri_20PRO_MBU.SFM
git mv 21_Ecclesiastes.usfm	    Manipuri_21ECC_MBU.SFM
git mv 22_Song_of_Solomon.usfm	    Manipuri_22SNG_MBU.SFM
git mv 23_Isaiah.usfm		    Manipuri_23ISA_MBU.SFM
git mv 24_Jeremiah.usfm	 	    Manipuri_24JER_MBU.SFM
git mv 25_Lamentations.usfm	    Manipuri_25LAM_MBU.SFM
git mv 26_Ezekiel.usfm		    Manipuri_26EZK_MBU.SFM
git mv 27_Daniel.usfm		    Manipuri_27DAN_MBU.SFM
git mv 28_Hosea.usfm		    Manipuri_28HOS_MBU.SFM
git mv 29_Joel.usfm		    Manipuri_29JOL_MBU.SFM
git mv 30_Amos.usfm		    Manipuri_30AMO_MBU.SFM
git mv 31_Obadiah.usfm		    Manipuri_31OBA_MBU.SFM
git mv 32_Jonah.usfm		    Manipuri_32JON_MBU.SFM
git mv 33_Micah.usfm		    Manipuri_33MIC_MBU.SFM
git mv 34_Nahum.usfm		    Manipuri_34NAM_MBU.SFM
git mv 35_Habakkuk.usfm	 	    Manipuri_35HAB_MBU.SFM
git mv 36_Zephaniah.usfm	    Manipuri_36ZEP_MBU.SFM
git mv 37_Haggai.usfm		    Manipuri_37HAG_MBU.SFM
git mv 38_Zechariah.usfm	    Manipuri_38ZEC_MBU.SFM
git mv 39_Malachi.usfm		    Manipuri_39MAL_MBU.SFM
git mv 40_Matthew.usfm		    Manipuri_41MAT_MBU.SFM
git mv 41_Mark.usfm		    Manipuri_42MRK_MBU.SFM
git mv 42_Luke.usfm		    Manipuri_43LUK_MBU.SFM
git mv 43_John.usfm		    Manipuri_44JHN_MBU.SFM
git mv 44_Acts.usfm		    Manipuri_45ACT_MBU.SFM
git mv 45_Romans.usfm		    Manipuri_46ROM_MBU.SFM
git mv 46_1_Corinthians.usfm	    Manipuri_471CO_MBU.SFM
git mv 47_2_Corinthians.usfm	    Manipuri_482CO_MBU.SFM
git mv 48_Galatians.usfm	    Manipuri_49GAL_MBU.SFM
git mv 49_Ephesians.usfm	    Manipuri_50EPH_MBU.SFM
git mv 50_Philippians.usfm	    Manipuri_51PHP_MBU.SFM
git mv 51_Colossians.usfm	    Manipuri_52COL_MBU.SFM
git mv 52_1_Thessalonians.usfm	    Manipuri_531TH_MBU.SFM
git mv 53_2_Thessalonians.usfm	    Manipuri_542TH_MBU.SFM
git mv 54_1_Timothy.usfm	    Manipuri_551TI_MBU.SFM
git mv 55_2_Timothy.usfm	    Manipuri_562TI_MBU.SFM
git mv 56_Titus.usfm		    Manipuri_57TIT_MBU.SFM
git mv 57_Philemon.usfm		    Manipuri_58PHM_MBU.SFM
git mv 58_Hebrews.usfm		    Manipuri_59HEB_MBU.SFM
git mv 59_James.usfm		    Manipuri_60JAS_MBU.SFM
git mv 60_1_Peter.usfm		    Manipuri_611PE_MBU.SFM
git mv 61_2_Peter.usfm		    Manipuri_622PE_MBU.SFM
git mv 62_1_John.usfm		    Manipuri_631JN_MBU.SFM
git mv 63_2_John.usfm		    Manipuri_642JN_MBU.SFM
git mv 64_3_John.usfm		    Manipuri_653JN_MBU.SFM
git mv 65_Jude.usfm		    Manipuri_66JUD_MBU.SFM
git mv 66_Revelation.usfm 	    Manipuri_67REV_MBU.SFM
git mv 95XXBMBUR.SFM Manipuri_95XXB_MBU.SFM
git mv 96XXCMBUR.SFM Manipuri_96XXC_MBU.SFM
git mv A9GLOMBUR.SFM Manipuri_A9GLO_MBU.SFM
